repos:
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.0
    hooks:
    -   id: gitleaks

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: detect-private-key
    -   id: detect-aws-credentials

-   repo: https://github.com/thoughtworks/talisman
    rev: 'v1.28.0'  # Update me!
    hooks:
    -   id: talisman-commit
        entry: cmd --githook pre-commit

#-   repo: local
#    hooks:
#    -   id: talisman-precommit
#        name: talisman
#        entry: bash -c 'if [ -n "${TALISMAN_HOME:-}" ]; then ${TALISMAN_HOME}/talisman_hook_script pre-commit; else echo "TALISMAN does not exist. Consider installing from https://github.com/thoughtworks/talisman . If you already have talisman installed, please ensure TALISMAN_HOME variable is set to where talisman_hook_script resides, for example, TALISMAN_HOME=${HOME}/.talisman/bin"; fi'
#        language: system
#        pass_filenames: false
#        types: [text]
#        verbose: true
